ALTER TABLE `AiModel`
  ADD COLUMN `group` VARCHAR(50) NOT NULL DEFAULT 'advanced',
  ADD COLUMN `tags` VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN `shortDescription` VARCHAR(255) NULL,
  ADD COLUMN `isRecommended` BOOLEAN NOT NULL DEFAULT false;
